### ISSUE TITLE
Ruby package problem

### ISSUE THREAD

**Issue by Saphyel** [malotor/vagrant_lamp#1]
I got this error : 
err: /Stage[main]/Ruby/Package[ruby]/ensure: change from purged to present failed: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install ruby1.9.1' returned 100: Reading package lists...
==> default: Building dependency tree...
==> default: Reading state information...
==> default: The following extra packages will be installed:
==> default:   libruby1.9.1 libyaml-0-2
==> default: Suggested packages:
==> default:   ruby1.9.1-examples ri1.9.1 graphviz ruby1.9.1-dev
==> default: The following NEW packages will be installed:
==> default:   libruby1.9.1 libyaml-0-2 ruby1.9.1
==> default: 0 upgraded, 3 newly installed, 0 to remove and 66 not upgraded.
==> default: Need to get 4192 kB of archives.
==> default: After this operation, 12.7 MB of additional disk space will be used.
==> default: Get:1 http://us.archive.ubuntu.com/ubuntu/ precise/main libyaml-0-2 amd64 0.1.4-2 [56.9 kB]
==> default: Err http://us.archive.ubuntu.com/ubuntu/ precise-updates/main libruby1.9.1 amd64 1.9.3.0-1ubuntu2
==> default:   404  Not Found [IP: 91.189.91.13 80]
==> default: Err http://us.archive.ubuntu.com/ubuntu/ precise-updates/main ruby1.9.1 amd64 1.9.3.0-1ubuntu2
==> default:   404  Not Found [IP: 91.189.91.13 80]
==> default: Failed to fetch http://us.archive.ubuntu.com/ubuntu/pool/main/r/ruby1.9.1/libruby1.9.1_1.9.3.0-1ubuntu2_amd64.deb  404  Not Found [IP: 91.189.91.13 80]
==> default: Failed to fetch http://us.archive.ubuntu.com/ubuntu/pool/main/r/ruby1.9.1/ruby1.9.1_1.9.3.0-1ubuntu2_amd64.deb  404  Not Found [IP: 91.189.91.13 80]
==> default: Fetched 56.9 kB in 0s (103 kB/s)
==> default: E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
==> default:

**Comment by malotor** [comment]
It seems like you can't access the apt repository. Maybe it's caused by a VM connectivity problem. Have you tried to do a ping from the client to a external machine?
